version: "3"
services:
  go:
    env_file:
      - .env
    build: ./
    container_name: go
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge